name: Publish hourly images

on:
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      -
        name: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: publish
        uses: docker/build-push-action@v2
        with:
          context: build/
          push: true
          tags: yeetzone/dontstarvetogether-data:latest
